apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: runner-application-gcp
spec:
  serviceName: "runner-application-statefulset"
  template:
    metadata:
      labels:
        app: runner-application
        type: cicd
    spec:
      containers:
        - name: runner-container
          image: gcr.io/{{PROJECT_ID}}/runner-application
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2375
            - name: RUNNER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ORGANIZATION
              value: {{GH_ORGANIZATION}}
            - name: REPO_URL
              value: https://github.com/$(ORGANIZATION)
            - name: RUNNER_LABELS
              value: {{GHR_LABELS}}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/key.json
            - name: GOOGLE_IMPERSONATE_SERVICE_ACCOUNT
              value: {{RUNNER_SA}}
          volumeMounts:
            - mountPath: /var/secrets
              name: jsonmount
              readOnly: true
        - name: dind-daemon
          image: docker:1.12.6-dind
          securityContext:
              privileged: true
          volumeMounts:
            - name: docker-graph-storage
              mountPath: /var/lib/docker
      volumes:
        - name: docker-graph-storage
          emptyDir: {}
        - name: jsonmount
          secret:
            secretName: json
  replicas: {{REPLICA_NUM}}
  selector:
    matchLabels:
      type: cicd
