apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: {{RUNNER_SA}}
  name: runner-account
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: runner-application-gcp
spec:
  serviceName: "runner-application-statefulset"
  template:
    metadata:
      labels:
        app: runner-application
        type: cicd
    spec:
      containers:
        - name: runner-container
          image: gcr.io/{{PROJECT_ID}}/runner-application
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2376
            - name: DOCKER_CERT_PATH
              value: /certs/client
            - name: DOCKER_TLS_VERIFY
              value: "1"
            - name: RUNNER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ORGANIZATION
              value: {{GH_ORGANIZATION}}
            - name: REPO_URL
              value: https://github.com/$(ORGANIZATION)
            - name: RUNNER_LABELS
              value: {{GHR_LABELS}}
          volumeMounts:
            - mountPath: /certs/client
              name: some-docker-certs-client
              readOnly: true
        - name: dind-daemon
          image: docker:20.10-dind # docker:1.12.6-dind
          env:
            - name: DOCKER_TLS_CERTDIR
              value: /certs
          securityContext:
              privileged: true
          volumeMounts:
            - name: docker-graph-storage
              mountPath: /var/lib/docker
            - name: some-docker-certs-ca
              mountPath: /certs/ca
            - name: some-docker-certs-client
              mountPath: /certs/client
      serviceAccountName: runner-account
      volumes:
        - name: docker-graph-storage
          emptyDir: {}
        - name: some-docker-certs-ca
          emptyDir: {}
        - name: some-docker-certs-client
          emptyDir: {}
  replicas: {{REPLICA_NUM}}
  selector:
    matchLabels:
      type: cicd
