apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner-app
spec:
  template:
    metadata:
      labels:
        app: runner-app
        type: cicd
    spec:
      containers:
        - name: runner-container
          image: airflowkubernetesui.azurecr.io/runner-container
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2375
            - name: PAT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tokenpat
                  key: tokenpat
            - name: RUNNER_NAME
              value: runner_airflow_kubernetes_ui_test
            - name: ORGANIZATION
              value: DsAirKube
            - name: REPO_URL
              value: https://github.com/DsAirKube
            - name: RUNNER_LABELS
              value: azzure,airflow
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/key.json
            - name: GOOGLE_IMPERSONATE_SERVICE_ACCOUNT
              value: airee-app-1@dsstream-airflowk8s.iam.gserviceaccount.com
          volumeMounts:
            - mountPath: /var/secrets
              name: jsonmount
              readOnly: true
        - name: dind-daemon
          image: docker:1.12.6-dind
          resources:
              requests:
                  cpu: 20m
                  memory: 512Mi
          securityContext:
              privileged: true
          volumeMounts:
            - name: docker-graph-storage
              mountPath: /var/lib/docker
      volumes:
        - name: docker-graph-storage
          emptyDir: {}
        - name: jsonmount
          secret:
            secretName: json
  replicas: 1
  selector:
    matchLabels:
      type: cicd
